CREATE DATABASE HealthMinister
GO
USE HealthMinister
GO
CREATE TABLE RoleGroup (
ID INT PRIMARY KEY IDENTITY,
Group_Name NVARCHAR(30) NOT NULL
);
GO
CREATE TABLE Sectors (
ID INT PRIMARY KEY IDENTITY,
Sec_Name NVARCHAR(30) NOT NULL
);
GO
CREATE TABLE FacilityType (
ID INT PRIMARY KEY IDENTITY,
Type NVARCHAR(30) NOT NULL
);
GO
CREATE TABLE Governorates (
ID INT PRIMARY KEY IDENTITY,
Gov_Name NVARCHAR(30) NOT NULL
);
GO
CREATE TABLE Departments (
ID INT PRIMARY KEY IDENTITY,
Dept_Name NVARCHAR(30) NOT NULL
);
GO
CREATE TABLE BasicGeneralFacilities (
WPlace UNIQUEIDENTIFIER PRIMARY KEY, -- DEFAULT NEWID(), --> To set GUID generated automatically
SecID INT FOREIGN KEY REFERENCES Sectors(ID),
FacID INT FOREIGN KEY REFERENCES FacilityType(ID),
GovID INT FOREIGN KEY REFERENCES Governorates(ID),
Name NVARCHAR(30),
National_Num NVARCHAR(30),
Area DECIMAL,
Seismic_Class_Reg NVARCHAR(30),
Comm_Cons_Code NVARCHAR(30),
Equity_Capital money,
Coin money, 
);
ALTER TABLE BasicGeneralFacilities ADD ID INT UNIQUE IDENTITY NOT NULL
GO
CREATE TABLE Hospitals (
ID INT PRIMARY KEY IDENTITY,
WPlace UNIQUEIDENTIFIER UNIQUE FOREIGN KEY REFERENCES BasicGeneralFacilities(WPlace),
Air_Strip BIT,
Blood_Bank_Unit BIT,
Chem_Injuries_Unit BIT,
Medical_Lab BIT,
Pharmacy BIT,
Num_Bones_OP_Rome INT
);
GO
CREATE TABLE DeptHOSBeds (
ID INT PRIMARY KEY IDENTITY,
HosID INT FOREIGN KEY REFERENCES Hospitals(ID),
DeptID INT FOREIGN KEY REFERENCES Departments(ID),
Num_Beds INT,
Num_Empty_Beds INT,
UDate DATETIME
);
GO
CREATE TABLE Users (
ID INT PRIMARY KEY IDENTITY,
WPlace UNIQUEIDENTIFIER FOREIGN KEY REFERENCES BasicGeneralFacilities(WPlace),
GroupID INT FOREIGN KEY REFERENCES RoleGroup(ID),
Phone INT,
Email NVARCHAR(30),
User_Name NVARCHAR(30),
User_Password NVARCHAR(30),
User_Address NVARCHAR(30),
Position NVARCHAR(30)
);
ALTER TABLE Users ADD First_Name NVARCHAR(30)
ALTER TABLE Users ADD Last_Name NVARCHAR(30)
GO
CREATE TABLE Directorates (
ID INT PRIMARY KEY IDENTITY,
WPlace UNIQUEIDENTIFIER UNIQUE FOREIGN KEY REFERENCES BasicGeneralFacilities(WPlace),
GovID INT FOREIGN KEY REFERENCES Governorates(ID),
Dir_Name NVARCHAR(30),
);
GO
CREATE TABLE Events (
ID INT PRIMARY KEY IDENTITY,
UserID INT FOREIGN KEY REFERENCES Users(ID),
DirID INT FOREIGN KEY REFERENCES Directorates(ID),
Events_Name NVARCHAR(30),
Events_Detils NVARCHAR(30),
Events_Loc NVARCHAR(30),
Reporting_Time DATETIME,
Sys_Date DATE,
Related_Parties NVARCHAR(30)
);
ALTER TABLE Events ADD Year VARCHAR(4)
