//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DB_First.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ImageID { get; set; }
        public byte[] ImageName { get; set; }
        public Nullable<System.Guid> propertyid { get; set; }
        public string ImageType { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
