//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EyadConsumer.ThawaniService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ThawaniService.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        EyadConsumer.ThawaniService.HelloWorldResponse HelloWorld(EyadConsumer.ThawaniService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<EyadConsumer.ThawaniService.HelloWorldResponse> HelloWorldAsync(EyadConsumer.ThawaniService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name simpleJson from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrder", ReplyAction="*")]
        EyadConsumer.ThawaniService.GetOrderResponse GetOrder(EyadConsumer.ThawaniService.GetOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<EyadConsumer.ThawaniService.GetOrderResponse> GetOrderAsync(EyadConsumer.ThawaniService.GetOrderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public EyadConsumer.ThawaniService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(EyadConsumer.ThawaniService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public EyadConsumer.ThawaniService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(EyadConsumer.ThawaniService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrder", Namespace="http://tempuri.org/", Order=0)]
        public EyadConsumer.ThawaniService.GetOrderRequestBody Body;
        
        public GetOrderRequest() {
        }
        
        public GetOrderRequest(EyadConsumer.ThawaniService.GetOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object simpleJson;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string auth;
        
        public GetOrderRequestBody() {
        }
        
        public GetOrderRequestBody(object simpleJson, string auth) {
            this.simpleJson = simpleJson;
            this.auth = auth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public EyadConsumer.ThawaniService.GetOrderResponseBody Body;
        
        public GetOrderResponse() {
        }
        
        public GetOrderResponse(EyadConsumer.ThawaniService.GetOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetOrderResponseBody {
        
        public GetOrderResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : EyadConsumer.ThawaniService.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<EyadConsumer.ThawaniService.WebService1Soap>, EyadConsumer.ThawaniService.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EyadConsumer.ThawaniService.HelloWorldResponse EyadConsumer.ThawaniService.WebService1Soap.HelloWorld(EyadConsumer.ThawaniService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            EyadConsumer.ThawaniService.HelloWorldRequest inValue = new EyadConsumer.ThawaniService.HelloWorldRequest();
            inValue.Body = new EyadConsumer.ThawaniService.HelloWorldRequestBody();
            EyadConsumer.ThawaniService.HelloWorldResponse retVal = ((EyadConsumer.ThawaniService.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EyadConsumer.ThawaniService.HelloWorldResponse> EyadConsumer.ThawaniService.WebService1Soap.HelloWorldAsync(EyadConsumer.ThawaniService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<EyadConsumer.ThawaniService.HelloWorldResponse> HelloWorldAsync() {
            EyadConsumer.ThawaniService.HelloWorldRequest inValue = new EyadConsumer.ThawaniService.HelloWorldRequest();
            inValue.Body = new EyadConsumer.ThawaniService.HelloWorldRequestBody();
            return ((EyadConsumer.ThawaniService.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EyadConsumer.ThawaniService.GetOrderResponse EyadConsumer.ThawaniService.WebService1Soap.GetOrder(EyadConsumer.ThawaniService.GetOrderRequest request) {
            return base.Channel.GetOrder(request);
        }
        
        public void GetOrder(object simpleJson, string auth) {
            EyadConsumer.ThawaniService.GetOrderRequest inValue = new EyadConsumer.ThawaniService.GetOrderRequest();
            inValue.Body = new EyadConsumer.ThawaniService.GetOrderRequestBody();
            inValue.Body.simpleJson = simpleJson;
            inValue.Body.auth = auth;
            EyadConsumer.ThawaniService.GetOrderResponse retVal = ((EyadConsumer.ThawaniService.WebService1Soap)(this)).GetOrder(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EyadConsumer.ThawaniService.GetOrderResponse> EyadConsumer.ThawaniService.WebService1Soap.GetOrderAsync(EyadConsumer.ThawaniService.GetOrderRequest request) {
            return base.Channel.GetOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<EyadConsumer.ThawaniService.GetOrderResponse> GetOrderAsync(object simpleJson, string auth) {
            EyadConsumer.ThawaniService.GetOrderRequest inValue = new EyadConsumer.ThawaniService.GetOrderRequest();
            inValue.Body = new EyadConsumer.ThawaniService.GetOrderRequestBody();
            inValue.Body.simpleJson = simpleJson;
            inValue.Body.auth = auth;
            return ((EyadConsumer.ThawaniService.WebService1Soap)(this)).GetOrderAsync(inValue);
        }
    }
}
